

```{r}
# region map
# maplink="https://raw.githubusercontent.com/ellenmw/spatialdata/master/cb_2018_us_region_500k.json"

# state map
maplink= "https://raw.githubusercontent.com/rslav/finalprojectSLAM/master/cb_2018_us_state_20m.json"

```

```{r}
# install.packages(c("geojsonio", "lwgeom", "rmapshaper", "tmap", "tmaptools"))
```

```{r}
library(lwgeom)
library(geojsonio)
library(ggplot2)
library(gridExtra)
library(cowplot)

PROJmap="+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
wazipMap=topojson_read(maplink,crs=PROJmap,stringsAsFactors = FALSE)


wazipMap

```

```{r}
object.size(wazipMap)
```

```{r}
wazipMap=st_make_valid(wazipMap)
```

```{r}
object.size(wazipMap)
```

```{r}

baseMap=ggplot(data=wazipMap) + geom_sf()
baseMap

```

```{r}
# Load data
eardatalink = "https://raw.githubusercontent.com/rslav/finalprojectSLAM/master/eardata.csv"
eardata<- read.csv(eardatalink)
data<- as.data.frame(eardata)
```

Preparing data merge by renaming merge variable to match my data:
```{r}
data
colnames(data)[2] <- "NAME"
```

Now merge the map data to our data:
```{r}
# put map first:
# merge two data frames by ID
total <- merge(wazipMap,data,by="NAME")
total

```

```{r}
#idea: show states that are always in top half or portion of the group for the indices; show states that are always doing poorly; compare to federal dependency

#yellow is good! blue is bad!
phimap=
  ggplot(data=total) + 
  scale_fill_viridis_c()+
  geom_sf(aes(fill=data$PHI)) +
    coord_sf(xlim = c(-170, -68), 
             ylim = c(19, 70)) +
  theme_classic() 


phimap

# low gini is good, so reversing the scale to keep yellow good!
total$gininew <- (1-total$Gini)

ginimap=
  ggplot(data=total) + 
  scale_fill_viridis_c()+
  geom_sf(aes(fill=total$gininew)) +
    coord_sf(xlim = c(-170, -68), 
             ylim = c(19, 70)) +
  theme_classic() 
ginimap

justicemap=
  ggplot(data=total) + 
  scale_fill_viridis_c()+
  geom_sf(aes(fill=total$JusticeIndex)) +
    coord_sf(xlim = c(-170, -68), 
             ylim = c(19, 70)) +
  theme_classic() 
justicemap

depmap=
  ggplot(data=total) + 
  scale_fill_viridis_c()+
  geom_sf(aes(fill=total$DependencyScore)) +
    coord_sf(xlim = c(-170, -68), 
             ylim = c(19, 70)) +
  theme_classic() 
depmap


```
```{r}
#create super index

summary(total$JusticeIndex)
#divide by 100 to get on a 0-1 scale
total$newjustice<-(total$JusticeIndex/100)

#subtract mean
summary(total$newjustice)
total$newjustice<-(total$newjustice-.3926)

#divide by SD
sd(total$newjustice)
total$newjustice <-(total$newjustice/.112602)

#a more-normally-distributed variable:
summary(total$newjustice)

#all positive values
total$newjustice <-(total$newjustice+2.1807253)
#0-1 scale
total$newjustice <-(total$newjustice/5)

#subtract mean
summary(total$Gini)
total$newgini<-(total$Gini-.4646)

#divide by SD
sd(total$newgini)
total$newgini <-(total$newgini/.02101533)

#a more-normally-distributed variable:
summary(total$newgini)
#all positive values
total$newgini <-(total$newgini+2.774167)
#0-1 scale
total$newgini <-(total$newgini/5.6)

#subtract mean
summary(total$PHI)
total$newphi<-(total$PHI-.2324)

#divide by SD
sd(total$newphi)
total$newphi <-(total$newphi/0.03823467)

#a more-normally-distributed variable:
summary(total$newphi)
#all positive values
total$newphi <-(total$newphi+1.5535638)
#0-1 scale
total$newphi <-(total$newphi/5)

total$superindex<- total$newphi+total$newjustice-total$newgini
summary(total$superindex)
```


```{r}
total$superindexhighlow =cut(total$superindex,
                          breaks = c(-0.47584,0.18394,1.04287),
                          labels = c("Low","High"))

summary(total$superindexhighlow)

summary(total$DependencyScore)
total$federaldependencyhighlow = cut(total$DependencyScore, 
                               breaks = c(10.6,37.77,85.82),
                               labels = c("Low","High"))
```


```{r}
finaldepmapall=
  ggplot(total) + 
  geom_sf(aes(fill=federaldependencyhighlow)) +
  coord_sf(xlim = c(-170, -68), 
          ylim = c(19, 70)) +
  theme_classic() +
  scale_fill_manual(values = c("#67a9cf", "#ef8a62"), 
                    name= "Federal Dependency")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
finaldepmapall

finaldepmapcontinental=
  ggplot(total) + 
  geom_sf(aes(fill=federaldependencyhighlow)) +
  coord_sf(xlim = c(-126, -68), 
          ylim = c(19, 50)) +
  theme_classic() +
  scale_fill_manual(values = c("#67a9cf", "#ef8a62"), 
                    name= "Federal Dependency")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
finaldepmapcontinental

finaldepmaphawaii=
  ggplot(total) + 
  geom_sf(aes(fill=federaldependencyhighlow)) +
  coord_sf(xlim = c(-160, -155), 
          ylim = c(18, 23)) +
  theme_classic() +
  scale_fill_manual(values = c("#67a9cf", "#ef8a62"), 
                    name= "Federal Dependency")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(), 
        legend.position = "none")
finaldepmaphawaii

finaldepmapalaska=
  ggplot(total) + 
  geom_sf(aes(fill=federaldependencyhighlow)) +
  coord_sf(xlim = c(-170, -135), 
          ylim = c(51, 75)) +
  theme_classic() +
  scale_fill_manual(values = c("#67a9cf", "#ef8a62"), 
                    name= "Federal Dependency")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(), 
        legend.position = "none")
finaldepmapalaska
```


```{r}
finalsupermapall=
  ggplot(total) + 
  geom_sf(aes(fill=superindexhighlow)) +
    coord_sf(xlim = c(-170, -68), 
             ylim = c(19, 70)) +
    theme_classic() +
  scale_fill_manual(values = c("#ef8a62", "#67a9cf"), 
                    name= "Super-Index Score")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
finalsupermapall

finalsupermapcontinental=
  ggplot(total) + 
  geom_sf(aes(fill=superindexhighlow)) +
  coord_sf(xlim = c(-126, -68), 
          ylim = c(19, 50)) +
    theme_classic() +
  scale_fill_manual(values = c("#ef8a62", "#67a9cf"), 
                    name= "Super-Index Score")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
finalsupermapcontinental

finalsupermaphawaii=
  ggplot(total) + 
  geom_sf(aes(fill=superindexhighlow)) +
  coord_sf(xlim = c(-160, -155), 
          ylim = c(18, 23)) +
    theme_classic() +
  scale_fill_manual(values = c("#ef8a62", "#67a9cf"), 
                    name= "Super-Index Score")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(), 
        legend.position = "none")
finalsupermaphawaii

finalsupermapalaska=
  ggplot(total) + 
  geom_sf(aes(fill=superindexhighlow)) +
  coord_sf(xlim = c(-170, -135), 
          ylim = c(51, 75)) +
    theme_classic() +
  scale_fill_manual(values = c("#ef8a62", "#67a9cf"), 
                    name= "Super-Index Score")+ 
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(), 
        legend.position = "none")
finalsupermapalaska
```


```{r}

supermap <-
  ggdraw() +
  draw_plot(finalsupermapcontinental) +
  draw_plot(finalsupermaphawaii, x = 0.15, y = .17, width = .3, height = .3) +
  draw_plot(finalsupermapalaska, x = 0.00, y = .1, width = .45, height = .45)

depmap <-
  ggdraw() +
  draw_plot(finaldepmapcontinental) +
  draw_plot(finaldepmaphawaii,x = 0.15, y = .17, width = .3, height = .3) +
  draw_plot(finaldepmapalaska, x = 0.00, y = .1, width = .45, height = .45)

stackmap<-plot_grid(supermap, depmap, nrow = 2)

```

