Ellen's Cluster Analysis

Data preparation:
```{r}
# Load data
eardatalink = "https://raw.githubusercontent.com/rslav/finalprojectSLAM/master/eardata.csv"
eardata<- read.csv(eardatalink)

data("eardata")
my_data <- eardata
# Remove any missing value (i.e, NA values for not available)
my_data <- na.omit(my_data)

#note, I removed the scaling code; not needed here bc data is already scaled

# View the first 5 rows
head(my_data, n = 5)

```

Determine the optimal number of clusters for k-means clustering:
```{r}
library("factoextra")
```

How about I isolate my desired variables...
```{r}
forjustice <- eardata[,c(4,5,6,7,8)] # justice indeces
```

You can compute and visualize PAM clustering as follow:
```{r}
# Compute PAM
library(cluster)
pam.res <- pam(forjustice, 4)
# Visualize
fviz_cluster(pam.res)

```

Let's do this for pregnancy health!
```{r}
forpreg <- eardata[,c(9, 10, 11, 12, 13, 14, 20, 21)] # state abbrev and pregnancy health indicators
```

You can compute and visualize PAM clustering as follow:
```{r}
# Compute PAM
library(cluster)
pam.res <- pam(forpreg, 4)
# Visualize
fviz_cluster(pam.res)

pam.res

```

